version: '3'

services:
  filebeat:
    restart: always
    hostname: filebeat
    build: ./filebeat
    volumes:
      - /root/app/docker/logs/:/usr/share/filebeat/docker/logs/
    links:
      - logstash
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:6.5.2
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601
  logstash:
    restart: always
    hostname: logstash
    build: ./logstash
    ports:
      - 5044:5044
    environment:
      LOG_LEVEL: error
    links:
      - elasticsearch
  elasticsearch:
    restart: always
    hostname: elasticsearch
    build: ./elasticsearch
    environment:
      - cluster.name=docker-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/logs:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200