version: '3'

services:
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:8.4.1
    logging:
      driver: "none"
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - "5601:5601"
  logstash:
    restart: always
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:8.4.1
    ports:
      - "5044:5044"
    logging:
      driver: "none"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LOG_LEVEL: error
    links:
      - elasticsearch
  elasticsearch:
    restart: always
    hostname: elasticsearch
    build: ./elasticsearch
#    logging:
#      driver: "none"
    environment:
      - cluster.name=docker-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9301:9300"