FROM docker.elastic.co/elasticsearch/elasticsearch:8.4.1
COPY --chown=elasticsearch:elasticsearch config/elasticsearch.yml /usr/share/elasticsearch/config/

CMD ["elasticsearch", "-Elogger.level=INFO"]